### ISSUE TITLE
Can `coloro` support `GBK` or `ANSI` ?

### ISSUE THREAD

**Issue by scillidan** [Insolita/coloro#1]
Some errors in `cmd` on `Windows`.

```cmd
λ coloro "D:\home\color.txt"
Traceback (most recent call last):
  File "C:\Users\scillidan\scoop\apps\python39\current\Scripts\coloro-script.py", line 33, in <module>
    sys.exit(load_entry_point('coloro', 'console_scripts', 'coloro')())
  File "d:\git\coloro\coloro\main.py", line 50, in main
    text = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 48: illegal multibyte sequence
```

**Comment by scillidan** [comment]
Maybe it's problem about [pyperclip](porhttps://github.com/asweigart/pyperclip).
For now, can change

https://github.com/Insolita/coloro/blob/84418ad02ee579c74374fafa0e5bf3752547ca33/coloro/main.py#L50

To 

```py
with open(args.text, encoding='utf-8') as f:
```

Then `coloro color.txt` worked.
And `cat .txt | coloro`, `coloro -c` still errors with `GBK`.
